drop table if exists cart CASCADE;
drop table if exists cart_item CASCADE;
drop table if exists product CASCADE;
drop table if exists user CASCADE;

create table product (
    id bigint generated by default as identity,
    created_by varchar(50) not null,
    created_date timestamp,
    last_modified_by varchar(50),
    last_modified_date timestamp,
    created_at timestamp not null,
    description varchar(255),
    image_url varchar(255),
    name varchar(255),
    price decimal(21, 2) not null,
    primary key (id)
);

create table cart (
    id bigint generated by default as identity,
    created_at timestamp not null,
    primary key (id)
);

create table cart_item (
    id bigint generated by default as identity,
    created_at timestamp not null,
    price decimal(21, 2) not null,
    quantity integer,
    cart_id bigint,
    product_id bigint,
    primary key (id),
    foreign key (cart_id) references cart(id),
    foreign key (product_id) references product(id)
);

create table user (
    id bigint generated by default as identity,
    created_by varchar(50) not null,
    created_date timestamp,
    last_modified_by varchar(50),
    last_modified_date timestamp,
    activated boolean not null,
    address varchar(200),
    email varchar(254),
    first_name varchar(50),
    last_name varchar(50),
    primary key (id)
);