DROP TABLE IF EXISTS product;

CREATE TABLE product (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(60) NOT NULL,
  image_url VARCHAR(500) NOT NULL,
  description VARCHAR(1000) DEFAULT NULL,
  price DECIMAL
);